export const AUTH_INITIATE = "AUTH_INITIATE"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_AUTO_CHECK = "AUTH_AUTO_CHECK"
export const REGISTER_INITIATE = "REGISTER_INITIATE"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const SHOW_ALERT_INITIATE = "SHOW_ALERT_INITIATE"
export const SHOW_ALERT_SHOW = "SHOW_ALERT_SHOW"
export const SHOW_ALERT_HIDE = "SHOW_ALERT_HIDE"
export const UPDATE_PROFILE_INITIATE = "UPDATE_PROFILE_INITIATE"
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS"
export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED"

export const LOAN_APPLY_INITIATE = "LOAN_APPLY_INITIATE"
export const LOAN_APPLY_SUCCESS = "LOAN_APPLY_SUCCESS"
export const LOAN_APPLY_ERROR = "LOAN_APPLY_ERROR"
export const LOAN_SAVE_FROM_API = "LOAN_SAVE_FROM_API"
export const LOAN_GET_API_INITIATE ="LOAN_GET_API_INITIATE"

 
// export { AUTH_INITIATE,AUTH_SUCCESS,AUTH_FAILED,AUTH_AUTOCHECK,REGISTER_INITIATE,REGISTER_SUCCESS,REGISTER_FAILED}