export const AUTH_INITIATE = "AUTH_INITIATE"
export const AUTH_SUCCESS = "AUTH_SUCCESS"
export const AUTH_FAILED = "AUTH_FAILED"
export const AUTH_AUTO_CHECK = "AUTH_AUTO_CHECK"
export const REGISTER_INITIATE = "REGISTER_INITIATE"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAILED = "REGISTER_FAILED"
export const SHOW_ALERT_INITIATE = "SHOW_ALERT_INITIATE"
export const SHOW_ALERT_SHOW = "SHOW_ALERT_SHOW"
export const SHOW_ALERT_HIDE = "SHOW_ALERT_HIDE"

// export { AUTH_INITIATE,AUTH_SUCCESS,AUTH_FAILED,AUTH_AUTOCHECK,REGISTER_INITIATE,REGISTER_SUCCESS,REGISTER_FAILED}